name: SonarQube Code Analysis
permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: null
      docker-compose:  
        type: string
      organization:  
        type: string
        default: amdigital-co-uk
      project:  
        type: string
    secrets:
      PKG_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
  
jobs:
  codeAnalysis:
    name: SonarQube Code Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu' 
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Install SonarCloud scanner
      run: |
        dotnet tool install --global dotnet-sonarscanner

    - name: Install dotnet coverage 
      run: |
        dotnet tool install --global dotnet-coverage

    - name: Login to GitHub packages
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        source-url: https://nuget.pkg.github.com/amdigital-co-uk/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.PKG_TOKEN}}
        
    - name: Report Package Vulnerabilities
      run: |
        dotnet build
        dotnet list package --vulnerable --include-transitive --format json > packageErrors.json
      continue-on-error: true

    - name: Format Package Vulnerabilities report
      run: |
        import json
        import os
        
        severity = {
            "Critical" : "CRITICAL",
            "High": "MAJOR",
            "Moderate": "MINOR",
            "Low": "INFO"
        }
        
        f = open('packageErrors.json')
        
        data = json.load(f)
        
        issues = []
        uniqueFolders = set()
        
        for projects in data['projects']:
            path = os.path.splitext(os.sep.join(os.path.normpath(projects["path"]).split(os.sep)[-3:]))[0] + ".json"
            uniqueFolders.add(path)
        
            for framework in projects['frameworks']:
                packages = []
                
                if "topLevelPackages" in framework:
                    packages = packages + framework['topLevelPackages']
        
                if "transitivePackages" in framework:
                    packages = packages + framework['transitivePackages']  
        
                for package in packages:
                    for vulnerability in package['vulnerabilities']:
                        issue = {
                            "engineId": "Dotnet Package",
                            "ruleId": "vulnerable-package",
                            "severity": severity[vulnerability["severity"]],
                            "type": "VULNERABILITY",
                            "primaryLocation": {
                                "message":  vulnerability["advisoryurl"],
                                "filePath": path
                            }
                        }
                        issues.append(issue);
        
        dictionary = {
            "issues": issues,
        }
        
        # Create files to attached issues too
        for filePath in uniqueFolders:
            # Remove top folder from folder path
            filePath = os.path.join(*(filePath.split(os.path.sep)[1:]))
                
            # Add current directory to file path
            filePath = os.path.join(os.getcwd(), filePath)
        
            if not os.path.exists(filePath):
                open(filePath, 'a').close()
        
        json_object = json.dumps(dictionary, indent=4)
        foldername = os.path.join(os.getenv("RUNNER_TEMP"), "dotnet-packages-report.json")

        print("Report complete saving to "+ foldername)

        with open(foldername, "w") as outfile:
            outfile.write(json_object)

      shell: python
        

    - name: Start containers
      if: ${{ inputs.docker-compose != '' }}
      run: docker compose -f ${{ inputs.docker-compose }} up -d

    - name: Build and analyze
      run: |
          dotnet-sonarscanner begin /k:"${{ inputs.organization }}_${{ inputs.project }}" /o:"${{ inputs.organization }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"  /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.externalIssuesReportPaths="${{ runner.temp }}/dotnet-packages-report.json"
          dotnet build --no-incremental
          dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 