# Run unit tests
name: Run Dotnet Tests
permissions:
  id-token: write
  contents: read

# Define Parameters
on:
  workflow_call:
    inputs:
      docker-compose:   # Path to docker-compose.yml file: If populated, spins up containers required for integration tests
        type: string
      dotnet-version:
        required: false
        type: string
        default: null
      aws-region:
        type: string
        default: us-east-1
      config-file-s3-root:
        required: false
        type: string
      config-file:
        required: false
        type: string
      copy-config-file-to-projects:
        required: false
        type: string
    secrets:
      PKG_TOKEN:
        required: true
      AWS_ROLE_ARN:
<<<<<<< HEAD
<<<<<<< HEAD
        required: false
=======
>>>>>>> ae70af0 (Adjust required inputs and checks)
=======
        required: false
>>>>>>> dcdae33 (Make AWS_ROLE_ARN not required)

jobs:
  dotnet-test:
    name: Run Dotnet Tests
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        if: ${{ inputs.config-file != ''}}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: ${{ inputs.aws-region }}

      # Copy config files from S3
      - name: Copy config file from s3 
        if: ${{ inputs.config-file != '' && inputs.config-file-s3-root != ''}}
        env:
          CONFIG_FILE: ${{ inputs.config-file }}
          CONFIG_FILE_S3_ROOT: ${{ inputs.config-file-s3-root }}
        run: |
          aws s3 cp $CONFIG_FILE_S3_ROOT/$CONFIG_FILE .

      # Copy config files to projects
      - name: Copy config file to projects
        if: ${{ inputs.config-file && inputs.copy-config-file-to-projects != '' }}
        env:
          PROJECTS: ${{ inputs.copy-config-file-to-projects }}
          CONFIG_FILE: ${{ inputs.config-file }}
        run: |
          for project in $PROJECTS
          do
            cp $CONFIG_FILE $project
          done

      # Spins up services via Docker-compose
      - name: Start containers
        if: ${{ inputs.docker-compose != '' }}
        run: docker compose -f ${{ inputs.docker-compose }} up -d
      
      # Login to GitHub packages
      - name: Login to GitHub packages
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          source-url: https://nuget.pkg.github.com/amdigital-co-uk/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.PKG_TOKEN}}
    
      # Run Unit Tests
      - name: Run Unit Tests
        run: dotnet test 