name: Read Service Version

# Define triggers for when the workflow will run
on:
  workflow_call:
    inputs:
      proj-path:
        description: 'project path'
        type: string
    outputs:
      version:
        value: ${{ jobs.read-version.outputs.version }}

jobs:
  read-version:
    name: Read Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: ${{ inputs.proj-path }}
