# CI workflow for Quartex NuGet packages
name: Build NuGET

on:
  workflow_call:
    inputs:
      skip-duplicate:   # Set to false to error when pushing duplicate versions
        required: true
        type: boolean
      pkg-src:          # URL of private GitHub packages feed to push to
        required: true
        type: string
      projects:         # Space-delimited string of .NET projects to build and pack
        required: true
        type: string
    secrets:
      PKG_TOKEN:
        required: true
jobs:
  nuget:
    name: Build NuGET
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Login to GitHub packages
      - name: Login to GitHub packages
        uses: actions/setup-dotnet@v1
        with:
          source-url: ${{ inputs.pkg-src }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PKG_TOKEN }}
      
      # Package libraries and push to GitHub packages
      - name: Create and push NuGet packages
        run: |
          flags="-k ${{secrets.GITHUB_TOKEN}} -s Source"
          [ "${{ inputs.skip-duplicate}}" = "true" ] && flags="$flags --skip-duplicate"
          for project in ${{ inputs.projects }}
          do
            cd $project
            cp ../../nuget.config .
            dotnet restore
            dotnet pack -c Release -o pkgs --no-restore
            dotnet nuget push pkgs/*.nupkg $flags
            cd ..
          done
