name: Add Git tags

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main

jobs:
  tag-version:
    name: Add Git tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Detect labels & tags
        id: detect-labels
        env:
          MAJOR: ${{ github.event.label.name == 'major' }}
          MINOR: ${{ github.event.label.name == 'minor' }}
          PATCH: ${{ github.event.label.name == 'patch' }}
        run: |
          # Get the latest tag and remove the leading 'v'
          version=$(git describe --tags --abbrev=0 | cut -dv -f2-)
          echo -n "version=$version, "

          # Set the version output
          echo "::set-output name=version::$version"

          # Set the bump output based on the label
          if [ "$MAJOR" = "true" ]
          then
              echo "major"
              echo "::set-output name=bump::major"
          elif [ "$MINOR" = "true" ]
          then
              echo "minor"
              echo "::set-output name=bump::minor"
          elif [ "$PATCH" = "true" ]
          then
              echo "patch"
              echo "::set-output name=bump::patch"
          else
              echo "none"
              echo "::set-output name=bump::none"
          fi

      - name: Install semver commandline
        run: |
          curl -L https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver -o semver
          chmod +x semver

      - name: Add version tags
        if: ${{ steps.detect-labels.outputs.bump != 'none' }}
        run: |

          TAGS=v$(./semver bump ${{ steps.detect-labels.outputs.bump }} ${{ steps.detect-labels.outputs.version }})

          for t in $(echo $TAGS | tr '.' '\n')
          do

              if [ -z "$tag" ]
              then
                  tag=$t
              else
                  tag=$tag.$t
              fi

              if [ "$(git tag | grep "^$tag$" | wc -l)" = "0" ]
              then
                  echo $tag does not exist
                  #git tag $tag
                  #git push origin $tag
              else
                  echo $tag exists
                  #git tag --delete $tag
                  #git push --delete origin $tag
                  #git tag $tag
                  #git push origin $tag
              fi

          done
      